// Code generated by mockery v2.34.1. DO NOT EDIT.

package recorder

import (
	mock "github.com/stretchr/testify/mock"
	v1 "k8s.io/api/admission/v1"
	unstructured "k8s.io/apimachinery/pkg/apis/meta/v1/unstructured"
)

// Recorder is an autogenerated mock type for the Recorder type
type Recorder struct {
	mock.Mock
}

type Recorder_Expecter struct {
	mock *mock.Mock
}

func (_m *Recorder) EXPECT() *Recorder_Expecter {
	return &Recorder_Expecter{mock: &_m.Mock}
}

// FromAdmissionRequest provides a mock function with given fields: oldObject, newObject, req
func (_m *Recorder) FromAdmissionRequest(oldObject *unstructured.Unstructured, newObject *unstructured.Unstructured, req *v1.AdmissionRequest) error {
	ret := _m.Called(oldObject, newObject, req)

	var r0 error
	if rf, ok := ret.Get(0).(func(*unstructured.Unstructured, *unstructured.Unstructured, *v1.AdmissionRequest) error); ok {
		r0 = rf(oldObject, newObject, req)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Recorder_FromAdmissionRequest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FromAdmissionRequest'
type Recorder_FromAdmissionRequest_Call struct {
	*mock.Call
}

// FromAdmissionRequest is a helper method to define mock.On call
//   - oldObject *unstructured.Unstructured
//   - newObject *unstructured.Unstructured
//   - req *v1.AdmissionRequest
func (_e *Recorder_Expecter) FromAdmissionRequest(oldObject interface{}, newObject interface{}, req interface{}) *Recorder_FromAdmissionRequest_Call {
	return &Recorder_FromAdmissionRequest_Call{Call: _e.mock.On("FromAdmissionRequest", oldObject, newObject, req)}
}

func (_c *Recorder_FromAdmissionRequest_Call) Run(run func(oldObject *unstructured.Unstructured, newObject *unstructured.Unstructured, req *v1.AdmissionRequest)) *Recorder_FromAdmissionRequest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*unstructured.Unstructured), args[1].(*unstructured.Unstructured), args[2].(*v1.AdmissionRequest))
	})
	return _c
}

func (_c *Recorder_FromAdmissionRequest_Call) Return(_a0 error) *Recorder_FromAdmissionRequest_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Recorder_FromAdmissionRequest_Call) RunAndReturn(run func(*unstructured.Unstructured, *unstructured.Unstructured, *v1.AdmissionRequest) error) *Recorder_FromAdmissionRequest_Call {
	_c.Call.Return(run)
	return _c
}

// String provides a mock function with given fields:
func (_m *Recorder) String() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// Recorder_String_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'String'
type Recorder_String_Call struct {
	*mock.Call
}

// String is a helper method to define mock.On call
func (_e *Recorder_Expecter) String() *Recorder_String_Call {
	return &Recorder_String_Call{Call: _e.mock.On("String")}
}

func (_c *Recorder_String_Call) Run(run func()) *Recorder_String_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Recorder_String_Call) Return(_a0 string) *Recorder_String_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Recorder_String_Call) RunAndReturn(run func() string) *Recorder_String_Call {
	_c.Call.Return(run)
	return _c
}

// NewRecorder creates a new instance of Recorder. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRecorder(t interface {
	mock.TestingT
	Cleanup(func())
}) *Recorder {
	mock := &Recorder{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
