# permissions for end users to edit configs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: config-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: krcrdr
    app.kubernetes.io/part-of: krcrdr
    app.kubernetes.io/managed-by: kustomize
  name: config-editor-role
rules:
- apiGroups:
  - recorder.blahonga.me
  resources:
  - configs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - recorder.blahonga.me
  resources:
  - configs/status
  verbs:
  - get
