openapi: "3.0.0"
info:
  version: 1.0.0
  title: krcrdr
  description: API for recording stuff
paths:
  /record:
    get:
      operationId: listRecords
      description: List all Records
      security:
        - BearerAuth:
          - "records:r"
      responses:
        200:
          description: the list of Records
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/recordWithID'
                maxItems: 100
    post:
      operationId: addRecord
      description: Add record
      security:
        - BearerAuth:
          - "records:w"
      requestBody:
        description: The record to insert. Returns the recordID
        required: true
        content:
          application/json:
            schema:
             $ref: '#/components/schemas/record'
      responses:
        201:
          description: The inserted record with the recordID
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/recordWithID'
components:
  schemas:
    record:
      properties: 
        changeTimestamp:
          type: string
          format: date-time
        operation:
          type: string
          enum:
          - CREATE
          - UPDATE
          - DELETE
        cluster:
          type: string
        userinfo:
          $ref: "#/components/schemas/io.k8s.api.authentication.v1.UserInfo"
        kind:
          $ref: "#/components/schemas/io.k8s.apimachinery.pkg.apis.meta.v1.GroupVersionKind"
        uid:
          type: string
        resource:
          $ref: "#/components/schemas/io.k8s.apimachinery.pkg.apis.meta.v1.GroupVersionResource"
        generation:
          type: integer
          format: int64
        jsonPatch:
          type: string
        jsonPatch6902:
          type: string
        diffString:
          type: string
        name:
          type: string
        namespace:
          type: string
        objectMeta:
          $ref: '#/components/schemas/io.k8s.apimachinery.pkg.apis.meta.v1.ObjectMeta'
      required:
        - name
        - cluster
        - namespace
        - kind
        - changeTimestamp
        - operation
        - generation
        - userInfo
        - jsonPatch
        - jsonPatch6902
        - diffString
        - objectMeta
        - resource
        - uid
    recordWithID:
      allOf:
        - $ref: '#/components/schemas/record'
        - properties:
            id:
              type: string
          required:
            - id
    error:
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
          description: Error code
        message:
          type: string
          description: Error message
    # K8s
    io.k8s.api.authentication.v1.UserInfo:
      description: >-
        UserInfo holds the information about the user needed to implement the
        user.Info interface.
      type: object
      properties:
        extra:
          description: Any additional information provided by the authenticator.
          type: object
          additionalProperties:
            type: array
            items:
              type: string
        groups:
          description: The names of groups this user is a part of.
          type: array
          items:
            type: string
        uid:
          description: >-
            A unique value that identifies this user across time. If this user is
            deleted and another user by the same name is added, they will have
            different UIDs.
          type: string
        username:
          description: The name that uniquely identifies this user among all active users.
          type: string

    io.k8s.apimachinery.pkg.apis.meta.v1.Time:
      format: date-time
      type: string
    io.k8s.apimachinery.pkg.apis.meta.v1.ObjectMeta:
      properties:
        annotations:
          additionalProperties:
            type: string
          type: object
        creationTimestamp:
          $ref: '#/components/schemas/io.k8s.apimachinery.pkg.apis.meta.v1.Time'
        deletionGracePeriodSeconds:
          format: int64
          type: integer
        deletionTimestamp:
          $ref: '#/components/schemas/io.k8s.apimachinery.pkg.apis.meta.v1.Time'
        finalizers:
          items:
            type: string
          type: array
          x-kubernetes-patch-strategy: merge
        generateName:
          type: string
        generation:
          format: int64
          type: integer
        labels:
          additionalProperties:
            type: string
          type: object
        managedFields:
          items:
            $ref: '#/components/schemas/io.k8s.apimachinery.pkg.apis.meta.v1.ManagedFieldsEntry'
          type: array
        name:
          type: string
        namespace:
          type: string
        ownerReferences:
          items:
            $ref: '#/components/schemas/io.k8s.apimachinery.pkg.apis.meta.v1.OwnerReference'
          type: array
          x-kubernetes-patch-merge-key: uid
          x-kubernetes-patch-strategy: merge
        resourceVersion:
          type: string
        selfLink:
          type: string
        uid:
          type: string
      type: object
    io.k8s.apimachinery.pkg.apis.meta.v1.ManagedFieldsEntry:
      properties:
        apiVersion:
          type: string
        fieldsType:
          type: string
        fieldsV1:
          $ref: '#/components/schemas/io.k8s.apimachinery.pkg.apis.meta.v1.FieldsV1'
        manager:
          type: string
        operation:
          type: string
        subresource:
          type: string
        time:
          $ref: '#/components/schemas/io.k8s.apimachinery.pkg.apis.meta.v1.Time'
      type: object
    io.k8s.apimachinery.pkg.apis.meta.v1.FieldsV1:
      type: object
    io.k8s.apimachinery.pkg.apis.meta.v1.OwnerReference:
      properties:
        apiVersion:
          description: API version of the referent.
          type: string
        blockOwnerDeletion:
          type: boolean
        controller:
          type: boolean
        kind:
          type: string
        name:
          type: string
        uid:
          type: string
      required:
        - apiVersion
        - kind
        - name
        - uid
      type: object

    io.k8s.apimachinery.pkg.apis.meta.v1.GroupVersionKind:
      description: >-
        GroupVersionKind unambiguously identifies a kind.  It doesn't anonymously
        include GroupVersion to avoid automatic coercion.  It doesn't use a
        GroupVersion to avoid custom marshalling
      type: object
      required:
        - group
        - version
        - kind
      properties:
        group:
          type: string
        kind:
          type: string
        version:
          type: string

    io.k8s.apimachinery.pkg.apis.meta.v1.GroupVersionResource:
      type: object
      required:
        - group
        - version
        - resource
      properties:
        group:
          type: string
        version:
          type: string
        resource:
          type: string

  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
security:
  - BearerAuth: [ ]


