// Code generated by mockery v2.34.1. DO NOT EDIT.

package store

import (
	context "context"

	apistore "github.com/cldmnky/krcrdr/internal/api/store"

	mock "github.com/stretchr/testify/mock"
)

// KVService is an autogenerated mock type for the KVService type
type KVService struct {
	mock.Mock
}

type KVService_Expecter struct {
	mock *mock.Mock
}

func (_m *KVService) EXPECT() *KVService_Expecter {
	return &KVService_Expecter{mock: &_m.Mock}
}

// CreateTenant provides a mock function with given fields: ctx, tenantId, tenant
func (_m *KVService) CreateTenant(ctx context.Context, tenantId string, tenant *apistore.Tenant) (*apistore.Tenant, error) {
	ret := _m.Called(ctx, tenantId, tenant)

	var r0 *apistore.Tenant
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *apistore.Tenant) (*apistore.Tenant, error)); ok {
		return rf(ctx, tenantId, tenant)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, *apistore.Tenant) *apistore.Tenant); ok {
		r0 = rf(ctx, tenantId, tenant)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*apistore.Tenant)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, *apistore.Tenant) error); ok {
		r1 = rf(ctx, tenantId, tenant)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// KVService_CreateTenant_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateTenant'
type KVService_CreateTenant_Call struct {
	*mock.Call
}

// CreateTenant is a helper method to define mock.On call
//   - ctx context.Context
//   - tenantId string
//   - tenant *apistore.Tenant
func (_e *KVService_Expecter) CreateTenant(ctx interface{}, tenantId interface{}, tenant interface{}) *KVService_CreateTenant_Call {
	return &KVService_CreateTenant_Call{Call: _e.mock.On("CreateTenant", ctx, tenantId, tenant)}
}

func (_c *KVService_CreateTenant_Call) Run(run func(ctx context.Context, tenantId string, tenant *apistore.Tenant)) *KVService_CreateTenant_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(*apistore.Tenant))
	})
	return _c
}

func (_c *KVService_CreateTenant_Call) Return(_a0 *apistore.Tenant, _a1 error) *KVService_CreateTenant_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *KVService_CreateTenant_Call) RunAndReturn(run func(context.Context, string, *apistore.Tenant) (*apistore.Tenant, error)) *KVService_CreateTenant_Call {
	_c.Call.Return(run)
	return _c
}

// GetTenant provides a mock function with given fields: ctx, tenantId
func (_m *KVService) GetTenant(ctx context.Context, tenantId string) (*apistore.Tenant, error) {
	ret := _m.Called(ctx, tenantId)

	var r0 *apistore.Tenant
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*apistore.Tenant, error)); ok {
		return rf(ctx, tenantId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *apistore.Tenant); ok {
		r0 = rf(ctx, tenantId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*apistore.Tenant)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, tenantId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// KVService_GetTenant_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTenant'
type KVService_GetTenant_Call struct {
	*mock.Call
}

// GetTenant is a helper method to define mock.On call
//   - ctx context.Context
//   - tenantId string
func (_e *KVService_Expecter) GetTenant(ctx interface{}, tenantId interface{}) *KVService_GetTenant_Call {
	return &KVService_GetTenant_Call{Call: _e.mock.On("GetTenant", ctx, tenantId)}
}

func (_c *KVService_GetTenant_Call) Run(run func(ctx context.Context, tenantId string)) *KVService_GetTenant_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *KVService_GetTenant_Call) Return(_a0 *apistore.Tenant, _a1 error) *KVService_GetTenant_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *KVService_GetTenant_Call) RunAndReturn(run func(context.Context, string) (*apistore.Tenant, error)) *KVService_GetTenant_Call {
	_c.Call.Return(run)
	return _c
}

// NewKVService creates a new instance of KVService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewKVService(t interface {
	mock.TestingT
	Cleanup(func())
}) *KVService {
	mock := &KVService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
