// Code generated by mockery v2.34.1. DO NOT EDIT.

package recorder

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	unstructured "k8s.io/apimachinery/pkg/apis/meta/v1/unstructured"

	v1 "k8s.io/api/admission/v1"
)

// Recorder is an autogenerated mock type for the Recorder type
type Recorder struct {
	mock.Mock
}

type Recorder_Expecter struct {
	mock *mock.Mock
}

func (_m *Recorder) EXPECT() *Recorder_Expecter {
	return &Recorder_Expecter{mock: &_m.Mock}
}

// FromAdmissionRequest provides a mock function with given fields: ctx, oldObject, newObject, req
func (_m *Recorder) FromAdmissionRequest(ctx context.Context, oldObject *unstructured.Unstructured, newObject *unstructured.Unstructured, req *v1.AdmissionRequest) error {
	ret := _m.Called(ctx, oldObject, newObject, req)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *unstructured.Unstructured, *unstructured.Unstructured, *v1.AdmissionRequest) error); ok {
		r0 = rf(ctx, oldObject, newObject, req)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Recorder_FromAdmissionRequest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FromAdmissionRequest'
type Recorder_FromAdmissionRequest_Call struct {
	*mock.Call
}

// FromAdmissionRequest is a helper method to define mock.On call
//   - ctx context.Context
//   - oldObject *unstructured.Unstructured
//   - newObject *unstructured.Unstructured
//   - req *v1.AdmissionRequest
func (_e *Recorder_Expecter) FromAdmissionRequest(ctx interface{}, oldObject interface{}, newObject interface{}, req interface{}) *Recorder_FromAdmissionRequest_Call {
	return &Recorder_FromAdmissionRequest_Call{Call: _e.mock.On("FromAdmissionRequest", ctx, oldObject, newObject, req)}
}

func (_c *Recorder_FromAdmissionRequest_Call) Run(run func(ctx context.Context, oldObject *unstructured.Unstructured, newObject *unstructured.Unstructured, req *v1.AdmissionRequest)) *Recorder_FromAdmissionRequest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*unstructured.Unstructured), args[2].(*unstructured.Unstructured), args[3].(*v1.AdmissionRequest))
	})
	return _c
}

func (_c *Recorder_FromAdmissionRequest_Call) Return(_a0 error) *Recorder_FromAdmissionRequest_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Recorder_FromAdmissionRequest_Call) RunAndReturn(run func(context.Context, *unstructured.Unstructured, *unstructured.Unstructured, *v1.AdmissionRequest) error) *Recorder_FromAdmissionRequest_Call {
	_c.Call.Return(run)
	return _c
}

// SendToApiServer provides a mock function with given fields: ctx
func (_m *Recorder) SendToApiServer(ctx context.Context) error {
	ret := _m.Called(ctx)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Recorder_SendToApiServer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendToApiServer'
type Recorder_SendToApiServer_Call struct {
	*mock.Call
}

// SendToApiServer is a helper method to define mock.On call
//   - ctx context.Context
func (_e *Recorder_Expecter) SendToApiServer(ctx interface{}) *Recorder_SendToApiServer_Call {
	return &Recorder_SendToApiServer_Call{Call: _e.mock.On("SendToApiServer", ctx)}
}

func (_c *Recorder_SendToApiServer_Call) Run(run func(ctx context.Context)) *Recorder_SendToApiServer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *Recorder_SendToApiServer_Call) Return(_a0 error) *Recorder_SendToApiServer_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Recorder_SendToApiServer_Call) RunAndReturn(run func(context.Context) error) *Recorder_SendToApiServer_Call {
	_c.Call.Return(run)
	return _c
}

// NewRecorder creates a new instance of Recorder. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRecorder(t interface {
	mock.TestingT
	Cleanup(func())
}) *Recorder {
	mock := &Recorder{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
